import type { Metadata } from "next";
import { Geist, Geist_Mono ,  } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import Providers from "@/components/show_loader_link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // title: "PAQS",
  description: "Generated by Mudasir Ahmed... ",
  icons:"/Images/title.png"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    
    <html lang="en">
      {/* <link rel="shortcut icon" href="/Svgs/Quora.svg" type="image/x-icon" /> */}
        <head><title className="text-yellow-400">PARS</title></head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased themx2 themx  `}
        >
        <Providers/>

        <Navbar/>
        {/* <Providers>{children}</Providers> */}
        {children}
        {/* </Providers> */}
        <Toaster/>
      </body>
    </html>
        </ClerkProvider>
  );
}
